language: python
python:
  - "2.7"

install:

script:
  - "./deploy.py" # or py.test for Python versions 3.5 and below

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: gh-pages
    all_branches: true
